version: '3.3'
services:
  asterisk:
    image: flaviostutz/freepbx
    ports:
      - 8080:80
      - 5060:5060/udp
      - 5160:5160/udp
      - 3306:3306
      - 18000-18100:18000-18100/udp
    restart: always
    environment:
      - ADMIN_PASSWORD=${PBX_PASSWORD}
    volumes:
      - backup:/backup
      - recordings:/var/spool/asterisk/monitor
volumes:
  backup:
  recordings:
