version: '3'

services:
  freepbx-app:
    container_name: freepbx-app
    image: tiredofit/freepbx
    ports:
      - 2000:80
      - 5060:5060/udp
      - 5160:5160/udp
      - 18000-18100:18000-18100/udp
      - 4445:4445
    volumes:
      - ./asterisk:/etc/asterisk
      - ./volumes/certs:/certs
      - ./volumes/data:/data
      - ./volumes/logs:/var/log
      - ./volumes/data/www:/var/www/html
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_NETWORK=${VIRTUAL_NETWORK}
      - VIRTUAL_PORT=${VIRTUAL_PORT}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - ZABBIX_HOSTNAME=${ZABBIX_HOSTNAME}
      - RTP_START=${RTP_START}
      - RTP_FINISH=${RTP_FINISH}
      - DB_EMBEDDED=${DB_EMBEDDED}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    restart: always
    networks:
      - proxy-tier
    cap_add:
      - NET_ADMIN
    privileged: true

  freepbx-db:
    container_name: freepbx-db
    image: tiredofit/mariadb
    restart: always
    volumes:
      - ./volumes/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    networks:
      - proxy-tier

  freepbx-db-backup:
    container_name: freepbx-db-backup
    image: tiredofit/db-backup
    links:
      - freepbx-db
    volumes:
      - ./volumes/dbbackup:/backup
    environment:
      - ZABBIX_HOSTNAME=${ZABBIX_HOSTNAME_BACKUP}
      - DB_HOST=${DB_HOST}
      - DB_TYPE=${DB_TYPE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_DUMP_FREQ=${DB_DUMP_FREQ}
      - DB_DUMP_BEGIN=${DB_DUMP_BEGIN}
      - DB_CLEANUP_TIME=${DB_CLEANUP_TIME}
      - COMPRESSION=${COMPRESSION}
      - MD5=${MD5}
    networks:
      - proxy-tier
    restart: always

networks:
  proxy-tier:
    driver: bridge
